### ISSUE TITLE
computeInfoVal2IFC processing time

### ISSUE THREAD

**Issue by teresa-canasbajo** [rdotsch/rcicr#107]
How long does it usually take for computeInfoVal2IFC to run? It is taking at least 3h for each subject! Is that normal?

Thanks

**Comment by rdotsch** [comment]
The first time it runs it needs to generate the reference distributions using simulation (with the number of iterations in the simualtion sepcified by the `iter` paramerer). Think of your computer participating in the reverse correlation experiment for 10000 times with the default parameters.

If every participant used the same stimuli from the .Rdata file, and you're calling `computeInfoVal2IFC()` iteratively for each participant, it should only take long for the first participant,  since rcicr stores the results of those simulations to the .Rdata file for later use. After that it should be fast.
