### ISSUE TITLE
Using all processors for generateCI() still takes extremely long and makes Mac unresponsive

### ISSUE THREAD

**Issue by linjansen** [rdotsch/rcicr#57]
When I want to create the group CIs using the generateCI() function, this function uses all four processors in my Mac so that it will go faster to create the CIs (at least I think that was the intention). However, it still takes extremely long (it's been busy for 30 minutes and is only at 58% of the first out of two group CIs). What's worse, however, is that it completely absorbs all capacity from the Mac, so that it is impossible to get any other work done in the meantime. In other words, I cannot use my Mac for perhaps an hour or so. I would prefer that the computation would go slower and that I could still work on other things while the computation runs in the background.

Perhaps it's an idea to give users the option how many processors they want the generateCI() function to use? So that they are not forced to wait and do nothing until the computation is finished. I do not have this problem when computing individual CIs with the function batchGenerateCI() or when visualizing a CI with the function autoscale(), but I have had this problem each time I use the generateCI() function to compute group CIs.

Update: it has now finally finished computing the two group CIs - it took 1 hour and 35 minutes (so the speed gain - if there is any - does not outweigh the disadvantage of not being able to work on the Mac for that long).

**Comment by rdotsch** [comment]
Hi Lin,

Thank you for registering the issue. Please keep the issues coming!

 By default generateCI uses all processor cores. There is already an option implemented to specify the number of the processors in the development version. If you want to use just a single core, use this:

`generateCI(..., n_cores=1)`

Hope this helps!

Ron

**Comment by aucuparia** [comment]
Hi Lin,

Just a note as to what may be happening in your case: I think it is likely that using all your cores push your RAM usage over its physical limit (I'm guessing that you have 8GB of RAM). When your OS runs out of RAM, it will start to use "swap space", which is simply a slice of your storage capacity (i.e. your hard drive) that acts as surrogate RAM. Because your hard drive is *much* slower than your RAM, use of swap space will become a bottleneck (a major one in your case).

Thanks for reporting. I think a sensible alternative to using all cores by default is to use all cores minus 1. This will prevent lock up. We'll have to address the memory consumption separately.

Best

**Comment by aucuparia** [comment]
@rdotsch I've reopened this issue because I do think this could use some refinement.

**Comment by aucuparia** [comment]
Let's figure out sensible parallel processing parameters in #64. I'm closing this one as a duplicate.
