### ISSUE TITLE
Use parallel::detectCores() - 1

### ISSUE THREAD

**Issue by rdotsch** [rdotsch/rcicr#64]
... so that there will always, by default, be one core left to control your machine.

**Comment by rdotsch** [comment]
Actually, it seems that the function is fastest when you use the number of physical cores (which in my case is detectCores() - 2).

**Comment by aucuparia** [comment]
@rdotsch I don't think that's *because* of the number of physical cores. Just a coincidence.

I've done some benchmarking to find out what the relation between CPU cores and process time is. Results as of now are not clear:

![cpu_cores_x_number_trials](https://cloud.githubusercontent.com/assets/17837210/26779378/69f87f38-49e5-11e7-819d-624bb264e374.png)

It seems as though there's only a difference between using 1 vs. multiple cores. A possible explanation is that there are some overhead costs involved with the parallel processing such that for a low number of trials the process time is mostly determined by the overhead costs. To test that, the plot should include process timing data for generation of larger stimulus sets. I limited the number of trials to 4, 8 and 16 so I wouldn't strain my CPU too much. The script below runs through 4, 8, 16, 32, 64, 128, 256 and 512 trials:

```
library(rcicr)

base_face_files <- list(FMNES = 'FMNES.jpg')

ntrials <- 1:8
ncores <- 1:4

results <- rep(NA, length(ntrials) * length(ncores))
dim(results) <- c(length(ntrials), length(ncores))

for (c in ncores) {
  for (t in ntrials) {
    results[t, c] <- system.time(stim_df <-
           generateStimuli2IFC(base_face_files = base_face_files,
                               n_trials = 2^(t + 1),
                               img_size = 512,
                               # mask = matrix(512 * 512, 512, 512),
                               maximize_baseimage_contrast = TRUE,
                               noise_type = 'sinusoid',
                               nscales = 5,
                               sigma = 25,
                               ncores = c,
                               returnAsDataframe = TRUE))['elapsed']
  }
}

df <- as.data.frame(t(results), row.names = c('1 core', '2 cores',
                                              '3 cores', '4 cores'))
x_axis <- 2^(ntrials+1)
png('cpu_cores_x_number_trials.png')
plot(x_axis, df[1, ], type = 'b', ylim = c(0, ceiling(max(df))),
     xlab = 'Trials', ylab = 'Duration (seconds)',
     main = 'Effect of n CPU cores * n trials on stim. gen. time')
points(x_axis, df[2, ], type = 'b', lty = 2)
points(x_axis, df[3, ], type = 'b', lty = 3)
points(x_axis, df[4, ], type = 'b', lty = 4)
legend('topleft', legend = c('1 core', paste0(2:4, ' cores')), lty = 1:4)
dev.off()
```

Please run it if you can and post the results here.
